workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop"  # run on main and develop

test_setup:
  stage: build  
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  script: 
    - echo "Git login"
    

pytest:
  stage: test
  variables:
    GIT_STRATEGY: none
  needs:
    ["test_setup"]
  script:
    - echo "Run Pytest"
    - python --version
    - python -m pytest -n 4


# pylint:
#   stage: test
#   variables:
#     GIT_STRATEGY: none
#   needs:
#     ["test_setup"]
#   script:
#     - echo "Run Linter"
#     - cd src/helpr
#     - pylint physics utilities tests


pages: 
  stage: deploy
  needs:
    ["test_setup"]
  script:
    - sphinx-build -v -b html src/docs/source/ public
  artifacts:
    paths:
      - public
  only:
    - main
